name: fennec_pg
description: a dart plugin to connect with postgres included orm.
version: 0.0.1
homepage: https://github.com/Fennec-Framework/fennec_pg

environment:
  sdk: ">=2.16.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies:
  crypto: ^3.0.2
