name: fennec_pg
description: this plugin belongs to Fennec Framework. it's a performant Postgresql Driver included ORM.
version: 0.0.7
homepage: https://github.com/Fennec-Framework/fennec_pg

environment:
  sdk: ">=2.16.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies:
  crypto: ^3.0.2
